In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
crunch = pd.read_csv('crunch.csv')
crunch

      Image_Name          Landmark         X         Y
0         crunch              NOSE  0.616662  0.549175
1         crunch    LEFT_EYE_INNER  0.622938  0.553962
2         crunch          LEFT_EYE  0.623152  0.556015
3         crunch    LEFT_EYE_OUTER  0.623366  0.558000
4         crunch   RIGHT_EYE_INNER  0.623387  0.552272
...          ...               ...       ...       ...
16891     crunch       RIGHT_ANKLE  0.494729  0.539278
16892     crunch         LEFT_HEEL  0.488297  0.544079
16893     crunch        RIGHT_HEEL  0.503988  0.548630
16894     crunch   LEFT_FOOT_INDEX  0.466703  0.556739
16895     crunch  RIGHT_FOOT_INDEX  0.482536  0.554353

[16896 rows x 4 columns]

In [4]:
crunch['Landmark'].unique()

array(['NOSE', 'LEFT_EYE_INNER', 'LEFT_EYE', 'LEFT_EYE_OUTER',
       'RIGHT_EYE_INNER', 'RIGHT_EYE', 'RIGHT_EYE_OUTER', 'LEFT_EAR',
       'RIGHT_EAR', 'MOUTH_LEFT', 'MOUTH_RIGHT', 'LEFT_SHOULDER',
       'RIGHT_SHOULDER', 'LEFT_ELBOW', 'RIGHT_ELBOW', 'LEFT_WRIST',
       'RIGHT_WRIST', 'LEFT_PINKY', 'RIGHT_PINKY', 'LEFT_INDEX',
       'RIGHT_INDEX', 'LEFT_THUMB', 'RIGHT_THUMB', 'LEFT_HIP',
       'RIGHT_HIP', 'LEFT_KNEE', 'RIGHT_KNEE', 'LEFT_ANKLE',
       'RIGHT_ANKLE', 'LEFT_HEEL', 'RIGHT_HEEL', 'LEFT_FOOT_INDEX',
       'RIGHT_FOOT_INDEX'], dtype=object)

In [7]:
select = ['LEFT_SHOULDER','RIGHT_SHOULDER','LEFT_ELBOW','RIGHT_ELBOW','LEFT_WRIST','RIGHT_WRIST','LEFT_HIP','RIGHT_HIP','LEFT_KNEE','RIGHT_KNEE','LEFT_ANKLE','RIGHT_ANKLE']
filtered_crunch = crunch[crunch['Landmark'].isin(select)]
filtered_crunch

      Image_Name        Landmark         X         Y
11        crunch   LEFT_SHOULDER  0.581389  0.612144
12        crunch  RIGHT_SHOULDER  0.605161  0.600847
13        crunch      LEFT_ELBOW  0.570155  0.592198
14        crunch     RIGHT_ELBOW  0.623261  0.589879
15        crunch      LEFT_WRIST  0.621829  0.618511
...          ...             ...       ...       ...
16887     crunch       RIGHT_HIP  0.528420  0.538994
16888     crunch       LEFT_KNEE  0.415858  0.550666
16889     crunch      RIGHT_KNEE  0.478083  0.471641
16890     crunch      LEFT_ANKLE  0.473890  0.548902
16891     crunch     RIGHT_ANKLE  0.494729  0.539278

[6144 rows x 4 columns]

In [9]:
crunch_reset=filtered_crunch.reset_index(drop=True)
crunch_reset

     Image_Name        Landmark         X         Y
0        crunch   LEFT_SHOULDER  0.581389  0.612144
1        crunch  RIGHT_SHOULDER  0.605161  0.600847
2        crunch      LEFT_ELBOW  0.570155  0.592198
3        crunch     RIGHT_ELBOW  0.623261  0.589879
4        crunch      LEFT_WRIST  0.621829  0.618511
...         ...             ...       ...       ...
6139     crunch       RIGHT_HIP  0.528420  0.538994
6140     crunch       LEFT_KNEE  0.415858  0.550666
6141     crunch      RIGHT_KNEE  0.478083  0.471641
6142     crunch      LEFT_ANKLE  0.473890  0.548902
6143     crunch     RIGHT_ANKLE  0.494729  0.539278

[6144 rows x 4 columns]

In [10]:
import pandas as pd

# pivot_table을 사용하여 X, Y 열을 재구조화
pivot_x = crunch_reset.pivot_table(index='Image_Name', columns='Landmark', values='X')
pivot_y = crunch_reset.pivot_table(index='Image_Name', columns='Landmark', values='Y')

# X 및 Y 값을 갖는 새 열 이름 생성
columns_x = [f'{col}_x' for col in pivot_x.columns]
columns_y = [f'{col}_y' for col in pivot_y.columns]

# 새 열 이름을 사용하여 데이터프레임 업데이트
pivot_x.columns = columns_x
pivot_y.columns = columns_y

# 두 데이터프레임을 하나로 병합
result_df = pd.concat([pivot_x, pivot_y], axis=1).reset_index()

# 결과 데이터프레임 출력
print(result_df)

  Image_Name  LEFT_ANKLE_x  LEFT_ELBOW_x  LEFT_HIP_x  LEFT_KNEE_x  \
0     crunch      0.434829      0.597903    0.509803     0.460725

   LEFT_SHOULDER_x  LEFT_WRIST_x  RIGHT_ANKLE_x  RIGHT_ELBOW_x  RIGHT_HIP_x  \
0          0.60496      0.638608       0.486401       0.646956     0.529715

   ...  LEFT_HIP_y  LEFT_KNEE_y  LEFT_SHOULDER_y  LEFT_WRIST_y  RIGHT_ANKLE_y  \
0  ...      0.5793     0.443454          0.62304      0.612415       0.548718

   RIGHT_ELBOW_y  RIGHT_HIP_y  RIGHT_KNEE_y  RIGHT_SHOULDER_y  RIGHT_WRIST_y
0       0.560602     0.546726      0.423043          0.592068       0.579609

[1 rows x 25 columns]

In [15]:
result_df

,Image_Name,LEFT_ANKLE_x,LEFT_ELBOW_x,LEFT_HIP_x,LEFT_KNEE_x,LEFT_SHOULDER_x,LEFT_WRIST_x,RIGHT_ANKLE_x,RIGHT_ELBOW_x,RIGHT_HIP_x,...,LEFT_HIP_y,LEFT_KNEE_y,LEFT_SHOULDER_y,LEFT_WRIST_y,RIGHT_ANKLE_y,RIGHT_ELBOW_y,RIGHT_HIP_y,RIGHT_KNEE_y,RIGHT_SHOULDER_y,RIGHT_WRIST_y
0,crunch,0.434829,0.597903,0.509803,0.460725,0.60496,0.638608,0.486401,0.646956,0.529715,...,0.5793,0.443454,0.62304,0.612415,0.548718,0.560602,0.546726,0.423043,0.592068,0.579609

In [13]:
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('train_data.csv')

# 'left'가 변수 이름에 들어간 열과 'label' 열을 선택하여 data_1로 저장
columns_to_select = [col for col in data.columns if 'left' in col] + ['label']
data_1 = data[columns_to_select].copy()

# data_1 확인
print(data_1.head())

   left_shoulder_x  left_shoulder_y  left_elbow_x  left_elbow_y  left_wrist_x  \
0         0.524863         0.555625      0.507023      0.651277      0.470332
1         0.522562         0.578823      0.507091      0.673083      0.466630
2         0.520056         0.552761      0.505723      0.643683      0.466629
3         0.521530         0.469933      0.503777      0.551353      0.463504
4         0.525848         0.398923      0.505607      0.468997      0.469968

   left_wrist_y  left_hip_x  left_hip_y  left_knee_x  left_knee_y  \
0      0.574889    0.561175    0.729054     0.523271     0.741088
1      0.600467    0.564359    0.752372     0.522961     0.749220
2      0.581453    0.563935    0.724415     0.525168     0.747676
3      0.485218    0.560847    0.655779     0.530541     0.738278
4      0.402994    0.559319    0.608572     0.537026     0.740349

   left_ankle_x  left_ankle_y  label
0      0.548493      0.903862  squat
1      0.547950      0.904223  squat
2      0.548582      0.904462  squat
3      0.549646      0.903296  squat
4      0.550732      0.903453  squat

In [14]:
data_1

,left_shoulder_x,left_shoulder_y,left_elbow_x,left_elbow_y,left_wrist_x,left_wrist_y,left_hip_x,left_hip_y,left_knee_x,left_knee_y,left_ankle_x,left_ankle_y,label
0,0.524863,0.555625,0.507023,0.651277,0.470332,0.574889,0.561175,0.729054,0.523271,0.741088,0.548493,0.903862,squat
1,0.522562,0.578823,0.507091,0.673083,0.466630,0.600467,0.564359,0.752372,0.522961,0.749220,0.547950,0.904223,squat
2,0.520056,0.552761,0.505723,0.643683,0.466629,0.581453,0.563935,0.724415,0.525168,0.747676,0.548582,0.904462,squat
3,0.521530,0.469933,0.503777,0.551353,0.463504,0.485218,0.560847,0.655779,0.530541,0.738278,0.549646,0.903296,squat
4,0.525848,0.398923,0.505607,0.468997,0.469968,0.402994,0.559319,0.608572,0.537026,0.740349,0.550732,0.903453,squat
...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,0.534212,0.288624,0.539146,0.413624,0.536072,0.300199,0.511820,0.513502,0.510333,0.713988,0.512870,0.879027,bicep curl
225,0.529975,0.294647,0.532500,0.414426,0.539644,0.302381,0.506847,0.515748,0.507203,0.715752,0.511841,0.878740,bicep curl
226,0.523020,0.304750,0.526981,0.419463,0.543463,0.319938,0.505268,0.519334,0.508118,0.713681,0.490385,0.863342,bicep curl
227,0.509316,0.302987,0.519792,0.405952,0.562132,0.379762,0.504535,0.518443,0.502848,0.698980,0.485635,0.860572,bicep curl
228,0.502411,0.295322,0.505328,0.401367,0.550061,0.432926,0.497192,0.516098,0.499128,0.698478,0.479537,0.872231,bicep curl